### ISSUE TITLE
Unable to push Part 2 with Part 1 no RST version

### ISSUE THREAD

**Issue by Jeerachee** [mattytrog/FUSEE_SUITE#2]
I'm having trouble getting the chip to mount to be able to copy over the Part 2 UF2 file.
I understand that I'm supposed to hold the VOL+ button for 20 seconds, but when exactly?
I've tried holding it for a couple minutes both at boot and after injecting the Samd21_Update payload to no avail.
Part 1 seems to be working properly otherwise as it's automatically putting the console into RCM mode but without Part 2 it's pretty much useless.

**Comment by mattyams** [comment]
I am guessing that your chip is already installed? You'll need to be able to press the actual button on your chip (assuming it has one) twice after entering SAMD Update mode, then plug in your computer USB. The folder should pop up on your computer then.

**Comment by Jeerachee** [comment]
> I am guessing that your chip is already installed? You'll need to be able to press the actual button on your chip (assuming it has one) twice after entering SAMD Update mode, then plug in your computer USB. The folder should pop up on your computer then.

I may be mistaken, but I believe the no reset version of part 1 disables this feature

**Comment by mattytrog** [comment]
Oh sheet... I haven't pushed part 2. I dropped it in but I didn't do the
final push. Best thing... Downgrade to other part 1 version. I could have
sworn I pushed v9.1. it supports new chips etc etc. I'm in Scarborough on
holiday. I'm guessing you cannot enter bootloader mode? Or is it just not
accepting any uf2?

**Comment by Jeerachee** [comment]
Yeah I can't enter bootloader mode, even by double pressing reset button

**Comment by mattytrog** [comment]
Ok... What version part 2 are u using?

**Comment by Jeerachee** [comment]
Well I was going to use the one that was in Old/PART_2_LATEST, I'm not 100% sure what the old version on there is. Is there some way to check since I can't hold VOL+ to get into the menu anymore?

**Comment by mattytrog** [comment]
If you have flashed part 1, your chip should be "erased" and go straight to
the uf2 bootloader. Led on trinket should be green. Part 1 triggers RCM.
Nothing more. Part 2 actually boots the unit.

So if you hold reset switch(which still resets btw) then press pwr to power
on, it should boot normal. If you are plugged into pc, a drive should pop
up.

The chip is either blank(triggers RCM only, then goes straight back to
bootloader mode), or you have part 2 on there, so you should be able to get
to menu. Let me know.

**Comment by Jeerachee** [comment]
Okay, so holding the reset button while powering on the console does allow it to boot normally, but when plugging it into my computer, a drive does not show up.

**Comment by mattytrog** [comment]
The screen needs to be off. It won't show if screen is "awake".

**Comment by Jeerachee** [comment]
Alright, the screen is off with the switch plugged in, and no drive is coming up. When I first installed the no reset UF2 the drive showed up and then disconnected 3-4 times before not showing up again, which seemed a bit odd to me, if that helps at all.

**Comment by mattytrog** [comment]
Hmmm... That is odd. What led lights are you seeing on the chip? Can you
see? What chip are you using? A trinket? A part 1 flash should erase the
chip. And it should trigger RCM and constantly reboot to "SWITCHBOOT" or
FUSEE drive(red breathing led). I've temporarily removed the no reset
bootloader until I can push the correct part 2 when I get home.

Tell me what the led is doing

**Comment by Jeerachee** [comment]
I'm using a trinket. The LED isn't even turning on, I had assumed that was intended with the no reset bootloader.

**Comment by mattytrog** [comment]
Hmmm... Does anything happen if you hold vol+ down for longer than 4
second? Any flashes?

If not, then your chip is actually looking for the uf2 and what you need to
do, is  plug in usb, power switch off... Then hold RST in and power on.
Switch should boot. Release and just wait. The drive should pop open. I'm
confident what's happening is the uf2 drive isn't being picked up by the pc.

**Comment by Jeerachee** [comment]
When should I hold down VOL+?

**Comment by mattytrog** [comment]
At any time. If you have a part 2 flashed (which you shouldn't have if you
have flashed part 1) then holding Vol+ down should start the chip options.
You should see a flash approx every two seconds.

ChipRCM is being triggered as you need to hold down reset to get it to boot
normally.

So... Part 1 is working- RCM is being triggered... There is no part 2
flashed. No LEDs. That means your chip is waiting for a pc connection.

You are hitting RCM every time. That means bootloader is working. You just
need to get the pc to see it. Normally this is when the LCD turns off when
the switch has fully booted. Or push Hekate and see if it pops up then.

**Comment by Jeerachee** [comment]
I just checked the continuity of my wires and they seem good and solid, holding VOL+ after booting normally, while screen is off but plugged in didn't do anything, no blinking LED. I tried what you just suggested about powering it on and waiting and it didn't show up. I tried on two other computers. It's reliably booting into RCM when I don't hold reset, no AutoRCM enabled through hekate. I'll try pushing hekate and see if the drive shows up from there. If it thinks there's a part 2 flashed for some reason, is there any way for me to force the bootloader to present the drive?

EDIT: Plugging the switch in after pushing hekate doesn't seem to do anything, but perhaps that's because the screen doesn't turn off?

**Comment by mattytrog** [comment]
If all else fails, and this becomes a real problem, I'll pull the release
altogether and I'll write an automatic recovery routine. In the meantime,
let's get your unit sorted.

The single colour LED(if fitted) should be breathing. The old part 1 used
to have both red single LED and RGB enabled on a trinket by default. But
there are new power on init routines in the new version.

I'm happy to either:
Sort your console.
Or
Send me your chip. I'll Reflash your part 1 and part 2 on my jig which
requires no computer
Or
I'll send you a replacement if you send me your non functional one.

This has been tested and retested on the newer qtpy chip as well as the
others. I just didn't push part 2 before I came away.

I'm a bit limited what I can do as I'm not home. But if it is bricked, it
is easily sorted. At no cost to you.

And I'll revise the release.

**Comment by Jeerachee** [comment]
Is it able to be reflashed with a jig without having to desolder from the console? If so I wouldn't mind paying for a jig myself to do it. I use the console regularly and would hate to have to desolder and resolder it

**Comment by mattytrog** [comment]
You need to be able to get to the swd pads on the bottom. It's how we flash
virgin chips.

**Comment by Jeerachee** [comment]
So it's going to have to be desoldered either way? There's no way I can push the payload that Part 2 includes manually in order to enter the bootloader drive through the chip assistant menu like the readme mentions?

**Comment by mattytrog** [comment]
It's looking like that. If there is no other way of getting the uf2 drive
to show....  But part 1 is running... And part 2 shouldn't even exist
because you flashed part 1. It's very peculiar. There will be a new version
of the no reset part 1 where this cannot happen again.

If it was a bad part 1 flash, I could understand it. But RCM is being
triggered. So it isn't a bad flash.

The Fusee drive should be showing. In fact you shouldn't be able to get rid
of it until a part 2 is flashed.

I'll investigate when I get home. The new version will have a fail-safe in
it. I didn't think it was necessary, on account f the chip being erased. So
our options remain that I'll get a chip sent to you, or I'll fix it at no
cost.

**Comment by Jeerachee** [comment]
If I get a jig set up, would I be able to dump the chip binary and send it to you to help with debugging? If so, I'd like to try fixing it myself if possible as it seems like a good learning experience, plus you're on holiday so I don't want to be a bother and I might be able to get it done before you're back

**Comment by mattytrog** [comment]
Ok... Well all the "jig" is, is a raspberry pi (with Ethernet for putty
purposes), plug the poorly board into the usb and there are two swd pads on
the bottom. I have an image on the gbatemp thread somewhere. It uses
openocd. Can take a few attempts. Or remove your chip(keep wires attached
to board) and fire it over to me. I know what's happened I think. For
whatever reason, it's attempting to boot a "part 2". Let me explain the
differences between the RST and non RST version... A delay of 500 mS and a
strap hold time of 100 mS, Vs a delay of 0 and strap hold time of 75mS.

I made it for speed. And because (normally) you can now access the
bootloader without the reset switch, I omitted the code for it. On the
understanding that the chip would indeed wipe itself when a new part 1 was
flashed. Every single chip I've tried(even the new ones, eg qtpy and Pi
Pico) have operated in exactly the same way. But hearing how this has
failed in your case, plus I didn't push the new version(it's sat there...
New diagrams for new chips too etc), I've pulled the no RST version. People
can only install an old version for the time being(I say old .. it's still
current).

But yes that's the drill. Flash my image to a pi(pi zero/2/ maybe 3, not
4), plug into ethernet, connect through putty and connect/flash

**Comment by Jeerachee** [comment]
Well with the unfortunate unavailability of Raspberry PIs at the moment and any commonly recommended JTAG/SWD debuggers, I think I'll have to put fixing and sending you the currently flashed image on hold. It seems the fastest and most available course of action is to just get a new trinket, which still seem readily available for quite cheap.

**Comment by mattytrog** [comment]
Yep. Or a QTPY. Where about are you? You in UK?

**Comment by Jeerachee** [comment]
I'm in the US

**Comment by mattytrog** [comment]
Ok... There is actually nothing wrong with your trinket. Just a bad flash.
100%fixable. Two more days I'll be home and can debug it properly. Though I
know what's happened. So... Options are Reflash a basic bootloader using a
raspberry pi jig, or get a fresh one. The old packages are just fine to use
until I can get v9.1.1 out on Friday

**Comment by mattytrog** [comment]
Ok... Let's run through this...

If you have flashed a part 1 with RST disabled, that should have erased the
chip. Thus, if you manage to boot into "normal" mode, a FUSEE drive should
pop up.

You should then be able to replace or update your file...

If you cannot boot "normal" mode because Chip RCM is constantly triggering,
power switch off, push back cover in(so reset switch is pressed, power
on)... Switch should boot normally. And if you plug into pc, you will see a
FUSEE drive.

**Comment by mattytrog** [comment]
The no reset version gets rid of the reset button because we use a register
to check on reboot. Basically, with the new version, you hold vol+ for 20
seconds and it enters bootloader mode.

**Comment by mattytrog** [comment]
Part 2 relies on part 1. Never the other way round.

Flashing part 1 normally erases the whole chip. Or it should do. Once the
chip has started(the first thing it does is drop the straps to gnd to
trigger RCM), the pointer moves to application start(part 2). If this isn't
present, or cannot run,  it will stay in bootloader mode. Ie constantly
showing the uf2 drive. You are getting no LEDs at all... Which would
normally lead me to think that part 1 has failed. But you are getting into
RCM every time. So it hasn't failed.

It's as though part 1 is running and it's jumping to a corrupted part 2.
But you would at least get some kind of LED. Even if it's stuck on. I'm
guessing you have removed the red led from the trinket(just using the RGB)
