### ISSUE TITLE
Right Joycon not getting recognized, when RCM/STRAP is connected to M0 Trinket

### ISSUE THREAD

**Issue by fischbyte** [mattytrog/FUSEE_SUITE#3]
Followed your tutorial on GBAtemp. Everything works as it should be, but my right Joycon is not getting recognized anymore when I slide it in. As soon as I unsolder the RCM/Strap cable from the Trinket, it works again. I think in deepsleep, the pin is all time LOW, which maybe causes those issues. Any ideas?

Btw thanks for your amazing work! :)

**Comment by mattytrog** [comment]
Hello Tim. Thank you for your kind words. What versions are you flashing on
to your chip? There was an unrelated issue with a commit I did regarding
the reset button... So your joycon isn't recognized... What happens if you
hold down the reset switch on the trinket m0 while booting? Is it
constantly connecting and disconnecting? Are you connected to usb power
during this time? Does it only happen when you are connected to usb power?
Can I have a look at your solder joint please? Also... Is the volume
graphic on the screen constantly showing?

Kind regards
Matty

**Comment by fischbyte** [comment]
Hi. USB power was not connected and I used the GitHub version from you DL: ~1Month ago. But I've maybe found the issue:
The long cable when desoldered from trinket and still soldered to switch, collects very slowly some GND (i don't know why this is happening. Everything is isolated with tape and I multimeter tested everything). My guess, that the long thin cable collects interference from the High frequency traces. 

Anyway I desoldered the long wire now completely and soldered a small resistor on the Joycon pins (4.7kOhm between pin 7 and 10). Now everything works as it should be :)

You can close this issue I think. Thanks for your help :)

**Comment by mattytrog** [comment]
Ok sir. I will. Keep checking back for updates probably later today. A few
bugs to quash and new chips added. Cheers
